name: 🔌 New CLI Adapter
description: Propose or contribute a new CLI adapter for Kage Bunshin
title: "[CLI Adapter]: "
labels: ["cli-adapter", "enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Want to add support for a new AI CLI tool? Great! Help us expand Kage Bunshin's capabilities.

        **Current Adapters**: Claude Code, Gemini CLI, Ollama, Auto-Claude

  - type: checkboxes
    id: search
    attributes:
      label: Pre-submission Checklist
      description: Please verify before submitting
      options:
        - label: I searched for existing adapter requests
          required: true
        - label: This CLI tool is publicly available or documented
          required: true
        - label: The CLI has a stable API/interface
          required: true

  - type: input
    id: cli_name
    attributes:
      label: CLI Tool Name
      description: What's the name of the CLI tool?
      placeholder: e.g., GitHub Copilot CLI, Cursor CLI, Aider, CodeWhisperer
    validations:
      required: true

  - type: input
    id: cli_url
    attributes:
      label: CLI Tool Website / Repository
      description: Link to the official website or GitHub repository
      placeholder: https://github.com/...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: CLI Tool Description
      description: What does this CLI tool do? What makes it unique?
      placeholder: GitHub Copilot CLI is an AI pair programmer that can suggest code, explain functions, and help debug...
    validations:
      required: true

  - type: dropdown
    id: cli_type
    attributes:
      label: CLI Tool Type
      description: What category does this CLI fall into?
      options:
        - Cloud AI Service (API-based, like Claude, GPT, Gemini)
        - Local LLM (runs on your machine, like Ollama, LM Studio)
        - Hybrid (can run both locally and remotely)
        - Code Assistant (specialized for coding tasks)
        - General Purpose AI
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: installation
    attributes:
      label: Installation / Setup
      description: How do you install and configure this CLI?
      placeholder: |
        ```bash
        npm install -g @githubnext/github-copilot-cli
        gh copilot auth
        ```
    validations:
      required: true

  - type: textarea
    id: usage
    attributes:
      label: Basic Usage Example
      description: How do you invoke this CLI to execute a task?
      placeholder: |
        ```bash
        gh copilot suggest "write a function to sort an array"
        ```
    validations:
      required: true

  - type: textarea
    id: output_format
    attributes:
      label: Output Format
      description: What does the CLI output look like? How should results be parsed?
      placeholder: |
        Outputs markdown text with code blocks:
        ```
        Here's a function to sort an array:
        ```python
        def sort_array(arr):
            return sorted(arr)
        ```
        ```

  - type: dropdown
    id: cost
    attributes:
      label: Cost / Pricing
      description: What's the cost model for this CLI?
      options:
        - Free / Open Source
        - Freemium (free tier + paid)
        - Paid (API usage costs)
        - Requires License/Subscription
        - Unknown
    validations:
      required: true

  - type: textarea
    id: api_features
    attributes:
      label: API Features / Capabilities
      description: What features does the CLI expose? (timeout control, streaming, context management, etc.)
      placeholder: |
        - Supports timeout via `--max-time` flag
        - Has `--json` output mode
        - Can pass context via files with `--context-file`
        - Streaming output with `--stream`

  - type: textarea
    id: limitations
    attributes:
      label: Known Limitations
      description: Any known issues, rate limits, or constraints?
      placeholder: |
        - Requires GitHub account
        - Rate limited to 50 requests/hour on free tier
        - No offline mode

  - type: textarea
    id: adapter_design
    attributes:
      label: Adapter Design Notes
      description: (Optional) Technical notes on how the adapter should work
      placeholder: |
        Should implement CLIAdapter interface:
        - execute(task, context) -> run CLI and capture output
        - parse_result(output) -> extract code/result from markdown
        - estimate_cost(task) -> calculate token usage

  - type: dropdown
    id: priority
    attributes:
      label: Community Interest
      description: How valuable would this adapter be?
      options:
        - High - Widely used tool, many would benefit
        - Medium - Niche but valuable
        - Low - Experimental or early stage
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Can you help implement this adapter?
      options:
        - label: I'm willing to implement this adapter
        - label: I can test this adapter once implemented
        - label: I have access to this CLI and can provide examples
        - label: I can write documentation for this adapter

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, examples, or references
      placeholder: Similar implementation in another project...
