name: ðŸ“ Documentation Improvement
description: Suggest improvements to documentation, guides, or examples
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Clear docs make the project better for everyone.

  - type: checkboxes
    id: search
    attributes:
      label: Pre-submission Checklist
      description: Please verify before submitting
      options:
        - label: I searched existing documentation issues
          required: true
        - label: I reviewed the current documentation
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What kind of documentation improvement is this?
      options:
        - Typo / Grammar / Formatting
        - Clarification / Better Explanation
        - Missing Information
        - Incorrect / Outdated Information
        - New Guide / Tutorial
        - Code Examples / Snippets
        - API Documentation
        - Installation / Setup Instructions
        - Troubleshooting Guide
        - Other
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Affected Documentation
      description: Which documentation needs improvement?
      options:
        - README.md
        - CONTRIBUTING.md
        - CODE_OF_CONDUCT.md
        - SECURITY.md
        - API Documentation (/docs Swagger UI)
        - Week Summaries (WEEK1_SUMMARY.md, etc.)
        - Code Comments / Docstrings
        - GitHub Wiki
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong or Missing?
      description: Describe the documentation issue
      placeholder: The installation instructions don't mention that PostgreSQL 15+ is required...
    validations:
      required: true

  - type: textarea
    id: location_details
    attributes:
      label: Specific Location
      description: Where exactly in the documentation is the issue?
      placeholder: |
        - **File**: README.md
        - **Section**: Installation > Prerequisites
        - **Line(s)**: Lines 62-65

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Add to the Prerequisites section:

        ```markdown
        - **PostgreSQL 15+** - Required for JSONB support
          ```bash
          # Ubuntu/Debian
          sudo apt install postgresql-15
          ```
        ```
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context / Why This Matters
      description: Why is this improvement important? Who does it help?
      placeholder: New users are getting confused during installation and opening issues about database errors...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Can you help with this documentation improvement?
      options:
        - label: I'm willing to submit a PR with the suggested changes
        - label: I can help review documentation PRs

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, links, or examples
      placeholder: Similar documentation in other projects...
