name: ✨ Feature Request
description: Suggest a new feature or enhancement for Kage Bunshin
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand your needs by filling out the sections below.

  - type: checkboxes
    id: search
    attributes:
      label: Pre-submission Checklist
      description: Please verify before submitting
      options:
        - label: I searched existing issues and feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I read the roadmap and this isn't already planned
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the motivation?
      placeholder: I'm frustrated when I need to manually retry failed tasks. It would be great if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Add automatic retry configuration to the task submission API:
        - Allow specifying retry count and backoff strategy
        - Expose retry status in progress events
        - Log retry attempts in database
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I could manually resubmit tasks via script, but that's not ideal because...

  - type: dropdown
    id: component
    attributes:
      label: Feature Category
      description: Which part of the system would this affect?
      options:
        - API / REST Endpoints
        - Task Orchestration / Execution
        - CLI Adapters (new adapter or improvements)
        - Database / Storage
        - Git Operations / Merging
        - SSE Streaming / Real-time Updates
        - Authentication / Security
        - Performance / Optimization
        - Documentation
        - Testing / CI/CD
        - Developer Experience
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority / Impact
      description: How important is this feature to you?
      options:
        - Critical - Blocking my usage
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples / Mockups
      description: Provide examples, code snippets, API designs, or mockups
      placeholder: |
        ```json
        POST /api/v1/tasks
        {
          "description": "...",
          "retry_config": {
            "max_attempts": 3,
            "backoff_strategy": "exponential"
          }
        }
        ```
      render: shell

  - type: textarea
    id: impact
    attributes:
      label: Use Cases
      description: Who would benefit from this feature? What use cases does it enable?
      placeholder: |
        - Production deployments where network failures are common
        - Long-running tasks that need resilience
        - Users who want fire-and-forget task submission

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: (Optional) Technical suggestions for how to implement this
      placeholder: Could use asyncio with exponential backoff in orchestrator/execution/parallel.py...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help implement this?
      options:
        - label: I'm willing to submit a PR to implement this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information, links, or references
      placeholder: Similar feature exists in Auto-Claude: https://...
